apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-standalone
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-standalone
    spec:
      containers:
        - name: mysql-standalone
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistant-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistant-storage
          persistentVolumeClaim:
            claimName: azure-managed-mysql-disk-pvc

