apiVersion: v1
kind: Service
metadata:
  name: productmgmt-webapp-service
  labels:
    app: productmgmt-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: product-management-webapp
  ports: 
    - port: 80
      targetPort: 8080